### ISSUE TITLE
Replace property NuGetPublishType by detecting type of NuGetPublishLocation

### ISSUE THREAD

**Issue by KarlProkupek** [SimplerSoftware/SS.NuGet.Publish#1]
Property `NuGetPublishType` is actually not necessary because I saw that you convert `NuGetPublishType` in targets file to `add` or `push` command.
I would suggest:
```
    <NuGetPublishCmd Condition="'$(NuGetPublishLocation.ToLower().StartsWith("https://"))' == 'false'">add</NuGetPublishCmd>
    <NuGetPublishCmd Condition="'$(NuGetPublishLocation.ToLower().StartsWith("https://"))' == 'true'">push</NuGetPublishCmd>
```
or something like that because I do not know exact syntax of these condition expressions.
Thank you for creating this package!

**Comment by johnwc** [comment]
Good point, we can just check if the value of location is a url. I'll look into this.

**Comment by johnwc** [comment]
This is in the latest version now.
