### ISSUE TITLE
Support Existing Visual Stuido project properties

### ISSUE THREAD

**Issue by ac-4** [SimplerSoftware/SS.NuGet.Publish#2]
Currently Visual Studio uses a standardized set of properties. It would be nice if this were supported.

```XML
	<PropertyGroup>
		<DebugType>embedded</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>1.0.0-alpah</Version>
		<RepositoryType>remote</RepositoryType>
		<RepositoryUrl>https://api.nuget.org/v3/index.json</RepositoryUrl>
	</PropertyGroup>
```

**Comment by johnwc** [comment]
Not really sure what you're asking here, the use of the Repository* properties?

**Comment by ac4-ltisolutions** [comment]
Correct. There may be a reason you are not using those properties, but these are the ones built into Visual Studio 2019 and 2022.

**Comment by johnwc** [comment]
Those are not for pointing to nuget. Those are for giving metadata about your source control repository's type and location.

That is what is used for the "Source Code" link when viewing a package on nuget gallery.
