### ISSUE TITLE
Don't push to nuget if already exists

### ISSUE THREAD

**Issue by canfucius** [SimplerSoftware/SS.NuGet.Publish#3]
I was testing out your nuget package (great job by the way) and when I tested if it will repush a package, I got this:

1>Pushing somecode.nupkg to 'https://pkgs.dev.azure.com/SomeCodeSoftware/_packaging/5848/nuget/v2/'...
1>  PUT https://pkgs.dev.azure.com/SomeCodeSoftware/_packaging/5848/nuget/v2/
1>MSBuild auto-detection: using msbuild version '17.1.0.52601' from 'C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\bin'.
1>  Conflict https://pkgs.dev.azure.com/SomeCodeSoftware/_packaging/5848/nuget/v2/ 1745ms
**1>To skip already published packages, use the option -SkipDuplicate**
1>Response status code does not indicate success: 409 (Conflict - The feed already contains 'SomeCode'. (DevOps Activity ID: B5657BDF-8014-4136-BD88-3A68D11AACAD)).

Can the SkipDuplicate option be added or be the default? For both local and remote push.

**Comment by nepton** [comment]
I got the same problem

**Comment by johnwc** [comment]
This is in the latest version now.
